### PR TITLE
Allow labels to be included or excluded based on the label name

### PR DESCRIPTION
**Pull request by phillipuniverse**
First of all, thanks for the awesome project! This served my needs almost perfectly.

I have a lot of labels that I didn't want to move over from 1 repo to another so I added functionality to manually include or exclude label names base on regex.

Thanks again!

### CODE REVIEW

**Comment by jvandemo** [comment]
@phillipuniverse &mdash; Thanks, really love this, great work!

Just a few questions:

- if you don't specify `includes` and `excludes`, does it still have the default behavior of copying all labels?
- when specifying both `includes` and `excludes` and a label matches both, is it included or excluded?

Really like where this is going. We just need to make sure it is properly documented and makes sense in all possible ways.

Looking forward to hearing your thoughts.

Thanks Phillip!

**Comment by phillipuniverse** [comment]
> if you don't specify includes and excludes, does it still have the default behavior of copying all labels?

Yes it does.

> when specifying both includes and excludes and a label matches both, is it included or excluded?

I think of the `includes` as "include all of these and exclude everything else". Therefore, I went with an approach that said if it matches both `includes` AND `excludes` (which I would technically argue as incorrect configuration) then the `include` takes precedence and it will be included.

In fact, with that statement if you specify an `includes` then it wouldn't actually make sense to populate the `excludes` with anything; anything not in `includes` is automatically excluded.

Do you think that makes sense?

**Comment by jvandemo** [comment]
> Do you think that makes sense?

Absolutely. My only concern is keeping the API as simple as possible for consumers.

The simplest way (to keep things as easy to understand as possible for consumers) is to only have one property `exclude`:

So:

```
exclude: ["type-bug", "severity-.*"]
```

would copy all labels except the ones specified in `exclude`.

Would be great if you could implement it like that so I can merge it because it's a great feature to add.

What do you think?

Thanks again for your effort!!

**Comment by jvandemo** [comment]
Closed due to lack of response. Feel free to re-open if needed. Thank you! 👍

**Pull request closed without merging**
