### PR TITLE
feat: add support for description

### LINKED ISSUE #8: Labels Description
GitHub already supports [Labels Description](https://github.com/blog/2505-label-improvements-emoji-descriptions-and-more). It might be a good idea to support it.

### PR DESCRIPTION
**Pull request by EdricChan03**
This PR aims to add support for the preview release of Labels API which introduced support for descriptions, emojis and more! See [here](https://developer.github.com/changes/2018-02-22-label-description-search-preview/) for more info.

This PR will close #8.

P.S. @jvandemo Can you check if the OAuth example works on your device? It worked on mine. Thanks!

This PR also fixes the following/introduces breaking changes:
- Use `owner` property instead of `user` as `user` property has been removed
- The code has been ES6ified, which will probably cause breaking changes for those running `4.9.1` and lower (See <https://node.green> for more info)
  - [Arrow functions support for NodeJS](https://node.green/#ES2015-misc-prototype-of-bound-functions-arrow-functions)
- Updates Travis to the latest version of NodeJS (version 10)

### CODE REVIEW

**Comment by jvandemo** [comment]
@Chan4077 &mdash; Awesome work! Will try it out asap 👍

**Comment by Chan4077** [comment]
Any update so far?

**Comment by jvandemo** [comment]
@Chan4077 &mdash; Not yet, I will have a look at it tomorrow 👍 Thanks and have a wonderful weekend!

**Comment by jvandemo** [comment]
@Chan4077 &mdash; I was unable to try out the changes today (due to work). If all goes well, I should be able to have a look at it on Wednesday 👍

**Comment by Chan4077** [comment]
@jvandemo Updates? It's been about 2 weeks already

**Comment by jvandemo** [comment]
@Chan4077 &mdash; I'm sorry, there were a couple of unexpected GDPR-related issues with clients that I had to follow up first. I have reserved a time block on Wednesday to have a look at your PR and will keep you posted on how it goes. Thanks again!

**Comment by jvandemo** [comment]
@Chan4077 &mdash; I finally had a chance to try out your PR.

It doesn't seem to work for me. I'm getting the following error:

```
Could not copy label: {"code":404,"status":"Not Found","message":"{\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"}"}
```

Would you be able to have a look at it?

Thanks in advance!

**Comment by Chan4077** [comment]
Hmm... when I tried that example, it worked on my end. What inputs did you enter in the example?

**Comment by Chan4077** [comment]
@jvandemo Did you manage to solve your issue? I couldn't find the cause of the issue.

**Comment by Chan4077** [comment]
FYI, I've just rebased all commits

**Comment by jvandemo** [comment]
@Chan4077 &mdash; Thank you! I'm currently traveling but will have a look at it at the end of next week 👍

**Comment by derberg** [comment]
@jvandemo hey, any updates, what is the ETA for merge and npm publishing? this feature is blocking me from using the library

**Comment by jvandemo** [comment]
@Chan4077 &mdash; Finally had a chance to review your update. Everything is working nicely now.

Thanks you for your contribution! 🏆

**Comment by jvandemo** [comment]
@derberg &mdash; Support for label descriptions has been released as v2.0.0 👍 

Feel free to let us know how it goes. Thanks!

**Comment by derberg** [comment]
@jvandemo Awesome, thanks a lot, project is awesome, already used it and worked pretty well. Saved several minutes of my life.

**Pull request merged**
